name: pipeline

# Trigger on push to master and selected pull request events targeting master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Try to sync the local repository to get up to speed with any changes in Cloud project
  cloud-sync:
    name: "Syncronize with Cloud"
    uses: ./.github/workflows/cloud-sync.yml
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  # Package and Deploy to Umbraco Cloud (only on push)
  cloud-deployment:
    name: "Deploy to Cloud"
    if: github.event_name == 'push'
    needs: cloud-sync
    uses: ./.github/workflows/cloud-deployment.yml
    with:
      newSha: ${{ needs.cloud-sync.outputs.newSha }}
    secrets:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      UMBRACO_CLOUD_API_KEY: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
